version: '3.4'

networks:
  integrationtest:
    driver: bridge

services:

  ##
  # Web Server which runs nginx+php
  web:
    image: devgeniem/ubuntu-docker-wordpress:php74
    ports:
      - 8080
    links:
      - db
      - redis
      - selenium
    volumes:
      # Sync files into this path with sync container
      - .:/var/www/project

      # Exclude theme's node_modules from the sync for performance reasons
      - /var/www/project/web/app/themes/THEMENAME/node_modules/

      # Use volume for xdebug trace and profiling so we can use analysing in other containers
      - /tmp/xdebug

      # In production uploads will be in /data/uploads/
      # This way let the container see them like in production
      - ./.docker/uploads:/var/www/uploads
    environment:
      # Small variable to tell if we are in production,testing or development
      # Don't use this in your code unless this is only option
      # We want to nearly identical codebase in production and development
      WP_ENV: testing

      WEB_UID: 1000
      WEB_GID: 1001

      # Set php to use redis for object cache & sessions
      REDIS_HOST: redis
      PHP_SESSION_HANDLER: redis
      PHP_SESSION_REDIS_DB: 0

      # Set error log path variables
      PHP_ERROR_LOG: /dev/stderr
      NGINX_ERROR_LOG: /dev/stderr

      # This is the default theme name WordPress will use
      WP_DEFAULT_THEME: THEMENAME

      # These are not actually used in gcloud
      NGINX_REDIS_CACHE_TTL_DEFAULT: "200 15m"

      # These variables can be used in nginx templates like .htpasswd
      BASIC_AUTH_USER: hello
      BASIC_AUTH_PASSWORD_HASH: world

      # These will be mapped automatically in development to jwilder/nginx-proxy
      VIRTUAL_HOST: 'asiakas.test, *.asiakas.test'
      VIRTUAL_PORT: 8080

      # This creates https certificate automatically when using gdev
      HTTPS_HOST: '*.asiakas.test'

      # Set project WP_SITEURL & WP_HOME from SERVER_NAME too
      SERVER_NAME: asiakas.test

      # Mysql details
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PWD: wordpress
      MYSQL_HOST: db

      # Raise the Nginx fastcgi timeout so that we can have longer debug sessions
      # This also raises php_execution_time
      NGINX_FASTCGI_TIMEOUT: 30

      # Mail settings
      SMTP_FROM: no-reply@asiakas.test
      # This will use local mail.test server
      SMTP_HOST: 172.17.0.1

      # Google Bucket dev settings
      GOOGLE_SERVICE_ACCOUNT_EMAIL: asiakas-dev@insert-account-email.com
      GOOGLE_CLOUD_STORAGE_BUCKET_NAME: asiakas-dev

    networks:
      integrationtest:
        aliases:
          - asiakas.test
          - web

    extra_hosts:
      - 'asiakas.test:127.0.0.1'
  ##
  # Use basic Mariadb container for database
  ##
  db:
    image: mariadb
    volumes:
      # Make database persistent
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    networks:
      integrationtest:
        aliases:
          - db

  ##
  # We use redis for wp object cache and php sessions
  ##
  redis:
    image: redis
    networks:
      integrationtest:
        aliases:
          - redis

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    networks:
      integrationtest:
        aliases:
          - selenium
    extra_hosts:
      - 'asiakas.test:172.18.0.5'
